# Generated by Django 5.2.12 on 2026-04-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('payment_id', models.IntegerField(blank=True, null=True)),
                ('delivery_address', models.TextField()),
                ('tracking_number', models.CharField(max_length=50, unique=True)),
                ('carrier', models.CharField(choices=[('DHL', 'DHL'), ('FedEx', 'FedEx')], max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pendiente'), ('In Transit', 'En Tránsito'), ('Delivered', 'Entregado')], default='Pending', max_length=20)),
                ('estimated_delivery_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tracking_number'], name='shipping_se_trackin_884316_idx'), models.Index(fields=['order_id'], name='shipping_se_order_i_9e7cc7_idx')],
            },
        ),
    ]
